### ISSUE TITLE
Add i18n helper script to import messages from other repos

### ISSUE THREAD

**Issue by MusikAnimal** [wikimedia/labs-tools-intuition#99]
In most of my projects, I use a Node.js script to import messages from other repos. Many messages like "Help" (for a help link) are identical, so putting them in a fresh repo that's hooked up to translatewiki.net just wastes translator's time. Instead, we can import all the existing translations.

The script can also be used to rename message keys, or remove messages (though the TWN bot probably does this automatically when changing en.json).

The XTools variant of the script is at https://github.com/x-tools/xtools/blob/master/i18n_helper.js.dist

Would it be helpful to include a script like this into Intuition? If so, should it be written in PHP instead of Node.js?

**Comment by samwilson** [comment]
This sounds useful. I'm imagining something like

    vendor/bin/intuition import -s ../some-other-project/i18n/ -d ./i18n/ 

would copy all matching messages from some-other-project to the current project's i18n directory.

How would we specify what messages to copy? It could just compare with en.json, but maybe one only wants a subset (as the current helper script does).

I'd be into helping do a PHP version. Can we use `symfony/console`?

**Comment by Krinkle** [comment]
My understanding is that the collective knowledge and experience as gathered and presented by translatewiki.net (primarily through development of MediaWiki and other WMF software) has led us to believe we should avoid transparent re-use of translations. See also <https://www.mediawiki.org/wiki/Localisation#Avoid_message_re-use>, which mentions this principle.

I'm excited about having a CLI entrypoint as described by @samwilson. That could set up localisation boilerplate for new (or existing) PHP projects. E.g. require the package, create `i18n/{en,qqq}.json` directory and files.  Perhaps even with an import another project's messages, to use as starting point.

However, if I understand correctly, you are looking to use this not to automate changes to a project's source repository, but rather as a command to run in the deployed ecosystem. As a way to semi-dynamically merge, or link, translations with those of another project. Is that right?

If so, then I think I would prefer not to encourage that. Instead, I'd like to capture the problem you're looking to solve and understand the underlying use case and work together to find a way that works well for everyone. It might even lead us back to this proposal. But I think we can go a step further and find something that's great translators, whilst also even easier for you in the end.

The status quo for MediaWiki is to manually duplicate the entries for English and Qqq, and let translatewiki.net handle it. Due to the translation index and how it provides quick suggestions from memory where there is a full or partial match, it should allow translations to be easily filled in.

There's certainly room for improvement. Two ideas that come to mind are 1) a utility to easily create `{{Identical}}` notes in Qqq, and 2) a CLI utility to copy given key/values from `en.json` and `qqq.json` to a destination project (similar to what you two described already). The changes would be committed to Git, and translations filled in after the next sync.

**Comment by MusikAnimal** [comment]
> However, if I understand correctly, you are looking to use this not to automate changes to a project's source repository, but rather as a command to run in the deployed ecosystem. As a way to semi-dynamically merge, or link, translations with those of another project. Is that right?

Hmm maybe. I'm talking about copying/importing translations from one repository to another, on your local machine. It's really the developer who needs to know when doing this is appropriate. Messages would need to be exactly the same in both apps, e.g. the label for a "Help" button. Anyway you're right, if we added this functionality others might still misuse it, e.g. importing "Edit" when you could be talking about revisions in one app but an Edit link in another. The context is different, so we wouldn't make assumptions. But in my case I'm importing from other apps I built, so I know the context.

> Due to the translation index and how it provides quick suggestions from memory where there is a full or partial match, it should allow translations to be easily filled in.

This is true but I've found it can still take quite a long time to gain interest from translators. All the while translations exist elsewhere but just not yet added to the app.

**Comment by samwilson** [comment]
>  E.g. require the package, create i18n/{en,qqq}.json directory and files. Perhaps even with an import another project's messages, to use as starting point.

This is about the sum of it I think. Except it couldn't require the package, because the command would be inside the package. :)

So this would be a local tool for developers who know the exact context of messages in other apps and definitely know that they want to duplicate them. I wanted to do this the other day because I'm building the language-chooser for SVG Translate and it's not yet available for translation so my chooser had no languages in it. I used @MusikAnimal's script to import a bunch of standard messages from grantmetrics—it was a one-off import and I added my own descriptions in `qqq.json`, rather than using `{{identical}}`... now I think about it I should be using that though...

Anyway, it sounds like a command for this needs to also add `{{identical}}`, e.g. 

    ./vendor/bin/intuition import --source=source/i18n/dir --dest=dest/i18n/dir --domain=foobar --msgs=msg1,msg2,msg3

would insert the given messages into all the lang files, and create the `{{identical|foobar-msg1}}` etc. entries in `qqq.json`. Maybe that list of messages could live in `.intuitionrc.json` or somewhere.

Of course, it could also be given a msg domain and list of messages and fetch them straight from TranslateWiki.net; that might be a future feature though.

**Comment by Nikerabbit** [comment]
Adding `identical` there is not enough. It just pulls in a sub page of the template where the list of messages is manually updated.

Ideally these should come automatically from our translation search...

**Comment by Krinkle** [comment]
> > E.g. require the package, create i18n/{en,qqq}.json directory and files. Perhaps even with an import another project's messages, to use as starting point.
> 
> [..] Except it couldn't require the package, because the command would be inside the package. :)

Aye, different kind of "require". I was referring to `composer require` and `composer.json#require`.

In other words, this "Intuition command-line utility" could, among the tasks it automates, also automatically the intuition library as a dependency to the project you're working on. E.g. to edit or create `composer.json` in the current directory.

**Comment by samwilson** [comment]
Oh, I was assuming the CLI tool would be *inside* this repository, and so only available *after* running `composer require krinkle/intuition` (at which point it'd be at `vendor/bin/intuition`).

Do you envisage this as a separate tool?
